spring:
  application:
    name: posts-service
  datasource:
    url: jdbc:mysql://localhost:3306/social_media
    username: raaxiim
    password: Raax11m17
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/dev

server:
  port: 8081


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

keycloak:
  clientId: demo
  clientSecret: demo
  scope: openid
  username: user-manager
  password: 1111
  serverUrl: http://localhost:9080
  realm: dev

storage:
  location: assets/posts